export const sampleArticles = [
  {
    keyword: "Nature",
    title: "The Beauty of Forests",
    text: "Some description text about forests and conservation.",
    date: "2025-01-21T10:00:00Z",
    source: "National Geographic",
    link: "https://example.com/forests",
    image: "https://picsum.photos/600/400?random=1",
    _id: "1",
  },
  {
    keyword: "Technology",
    title: "AI is Changing the World",
    text: "A summary describing how AI impacts everyday life.",
    date: "2025-01-18T14:30:00Z",
    source: "TechCrunch",
    link: "https://example.com/ai",
    image: "https://picsum.photos/600/400?random=2",
    _id: "2",
  },
  {
    keyword: "Sports",
    title: "The Championship Game Recap",
    text: "An article about the big game last night.",
    date: "2025-01-20T20:15:00Z",
    source: "ESPN",
    link: "https://example.com/sports",
    image: "https://picsum.photos/600/400?random=3",
    _id: "3",
  },

  {
    keyword: "Technology",
    title: "Quantum Computing Reaches New Milestone",
    text: "Researchers demonstrate a 500-qubit quantum processor with improved error correction.",
    date: "2025-01-22T09:45:00Z",
    source: "Wired",
    link: "https://example.com/quantum",
    image: "https://picsum.photos/600/400?random=4",
    _id: "4",
  },
  {
    keyword: "Technology",
    title: "New Smartphone Uses Holographic Display",
    text: "A startup unveils the world's first consumer holographic smartphone.",
    date: "2025-01-23T07:20:00Z",
    source: "The Verge",
    link: "https://example.com/holographic-phone",
    image: "https://picsum.photos/600/400?random=5",
    _id: "5",
  },

  {
    keyword: "Sci-Fi",
    title: "New Starship Series Breaks Streaming Records",
    text: "The reboot of the classic sci-fi franchise becomes the most-watched premiere in platform history.",
    date: "2025-01-19T12:00:00Z",
    source: "IGN",
    link: "https://example.com/starship-series",
    image: "https://picsum.photos/600/400?random=6",
    _id: "6",
  },
  {
    keyword: "Sci-Fi",
    title: "Scientists Discover Planet Resembling Pandora",
    text: "Astronomers find a lush exoplanet with bioluminescent life-like features.",
    date: "2025-01-17T18:05:00Z",
    source: "Space.com",
    link: "https://example.com/pandora-planet",
    image: "https://picsum.photos/600/400?random=7",
    _id: "7",
  },

  {
    keyword: "Space",
    title: "NASA Confirms Water Beneath the Surface of Europa",
    text: "New radar scans show deeper oceans than previously thought.",
    date: "2025-01-15T11:00:00Z",
    source: "NASA",
    link: "https://example.com/europa-water",
    image: "https://picsum.photos/600/400?random=8",
    _id: "8",
  },
  {
    keyword: "Space",
    title: "Mars Colony Habitat Prototype Completed",
    text: "SpaceX and NASA unveil the first fully functional Mars habitat model.",
    date: "2025-01-25T16:40:00Z",
    source: "SpaceX News",
    link: "https://example.com/mars-habitat",
    image: "https://picsum.photos/600/400?random=9",
    _id: "9",
  },

  {
    keyword: "Gaming",
    title: "Open-World RPG Announces Expansion",
    text: "The hit sci-fi RPG gets a massive expansion featuring new planets.",
    date: "2025-01-14T22:10:00Z",
    source: "GameSpot",
    link: "https://example.com/rpg-expansion",
    image: "https://picsum.photos/600/400?random=10",
    _id: "10",
  },

  {
    keyword: "Business",
    title: "Tech Giants Form New Partnership on AI Safety",
    text: "Major companies collaborate to establish industry-wide AI guidelines.",
    date: "2025-01-16T09:00:00Z",
    source: "Reuters",
    link: "https://example.com/ai-safety",
    image: "https://picsum.photos/600/400?random=11",
    _id: "11",
  },

  {
    keyword: "Health",
    title: "Breakthrough in Cancer Detection",
    text: "New blood test can detect early cancer signs with 94% accuracy.",
    date: "2025-01-20T08:10:00Z",
    source: "Medical News Today",
    link: "https://example.com/cancer-detection",
    image: "https://picsum.photos/600/400?random=12",
    _id: "12",
  },
];
